language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: r9yMtxsQ8+KgMSsKrtpL1b0nFeupt9NlXBCxv5GLuE/F7dNABGJr3Qd6RTKPJSdz3Tb8iiT8cRn77Hy8opB8ETKXKf2uSgvZIy+a+egsRA80KK+AFp5F3Lv7XA+4jGxYqV26EkxX/NIq1MfFIow4Jt+sau+TlKQtg8SeULZ/02iY6BM53iWRPzDye+xf6I8B+HKQBtlTgTfsAonPeiorb+f1BVav09U/XNRkwyF1gHnUvxyK3W/zAXqwg63nTCK4jwXanMLkM56H2IwheY2jk9/AviNwDqfcJoDSl+bB2raywhB6VOhPf+nPmmdRaLhXKwptcKyb5S1imyGSGdEhCjRs2IGk5HZDbcjk7AeS131ne8BcY+FWAs0LbCh0DH6vEu2nQye6IgvIvXjIFIvzBxWpk6mFfdICYUkBlcDg5wIFDMoSVwbdYqC6zxnOOkETAnEnZmVphybRvI8z8PVR4K+Zkc080Y7/c1JsCp9gLVHBnmTJ8bs2r5lE8l5z2FzGQWpR2RMx3lWXpVj/TjsSGyH+nXwQVJ2aYeCv/qQ8EJutQMeTKcJi1FNZlM2d306YeSDXkJTVVZIEpWW660zbvJmg0kOUhVtsP32EuSOULgz48VSvHcGJHPOtG6ljruhTm92Nom7BYFF0ziu71mWrj72/N6mOFB1eH1xZwVqza1w=
